"""Automated proton-coupled electron transfer (PCET) rate calculations."""

from importlib.metadata import version as _version

from .constants import (
    A2Bohr,
    A2cm,
    A2nm,
    Bohr2A,
    Da2me,
    Debye2au,
    Ha2eV,
    Ha2kcal,
    au2s,
    c,
    cm2A,
    eV2Ha,
    eV2kcal,
    eV2wn,
    h,
    hbar,
    kB,
    kcal2eV,
    kcal2Ha,
    massD,
    massH,
    me2Da,
    nm2A,
    wn2eV,
)
from .edl import fermi_distribution, make_edl_model
from .fgh import fgh_1d
from .kappa import KappaCoupling
from .potentials import (
    fit_bspline,
    fit_poly6,
    fit_poly8,
    gaussian,
    inverted_morse,
    make_double_well,
    make_inverted_morse,
    make_morse,
    morse,
    poly6,
    poly8,
)
from .rates import PCET
from .utils import find_roots, is_array, is_number

__version__ = _version("autopcet")

__all__ = [
    "PCET",
    "A2Bohr",
    "A2cm",
    "A2nm",
    "Bohr2A",
    "Da2me",
    "Debye2au",
    "Ha2eV",
    "Ha2kcal",
    "KappaCoupling",
    "__version__",
    "au2s",
    "c",
    "cm2A",
    "eV2Ha",
    "eV2kcal",
    "eV2wn",
    "fermi_distribution",
    "fgh_1d",
    "find_roots",
    "fit_bspline",
    "fit_poly6",
    "fit_poly8",
    "gaussian",
    "h",
    "hbar",
    "inverted_morse",
    "is_array",
    "is_number",
    "kB",
    "kcal2Ha",
    "kcal2eV",
    "make_double_well",
    "make_edl_model",
    "make_inverted_morse",
    "make_morse",
    "massD",
    "massH",
    "me2Da",
    "morse",
    "nm2A",
    "poly6",
    "poly8",
    "wn2eV",
]
