"""Align the reactant and product structures of a PCET reaction and average them.

The two structures are overlaid so their proton donor and acceptor are
superimposed along Z with the midpoint at the origin, the product is then
rotated about Z to minimize the RMSD to the reactant, and the averaged geometry
is written out. The proton is optimized on that averaged geometry -- on the
donor for the reactant, on the acceptor for the product -- before the proton
potentials are scanned with ``autopcet-scan-proton``.

Donor and acceptor indices are 1-based, as printed by most quantum chemistry
programs. The atoms must appear in the same order in both structures.
"""

import argparse
import math
from pathlib import Path

from ..structure import (
    align_da_to_z,
    average_structures,
    centre_da_midpoint,
    minimize_rmsd_rotation,
    rotation_about_z,
    round_to_xyz_precision,
    write_xyz,
)
from ._io import read_structure


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="autopcet-align-average", description=__doc__)
    parser.add_argument(
        "-r",
        "--reactant",
        dest="reactant_path",
        required=True,
        help="structure file with the reactant",
    )
    parser.add_argument(
        "-p",
        "--product",
        dest="product_path",
        required=True,
        help="structure file with the product",
    )
    parser.add_argument(
        "-o",
        "--output",
        dest="output_path",
        default="AVERAGE_STRUCTURE.xyz",
        help="xyz file to write the average structure to (default: %(default)s)",
    )
    parser.add_argument(
        "--r-donor",
        type=int,
        dest="reactant_donor",
        required=True,
        help="donor atom index in the reactant structure",
    )
    parser.add_argument(
        "--r-acceptor",
        type=int,
        dest="reactant_acceptor",
        required=True,
        help="acceptor atom index in the reactant structure",
    )
    parser.add_argument(
        "--p-donor",
        type=int,
        dest="product_donor",
        required=True,
        help="donor atom index in the product structure",
    )
    parser.add_argument(
        "--p-acceptor",
        type=int,
        dest="product_acceptor",
        required=True,
        help="acceptor atom index in the product structure",
    )
    return parser


def aligned_path(path: str, suffix: str) -> Path:
    """Name for an intermediate aligned structure, alongside its input."""
    original = Path(path)
    return original.with_name(original.stem + suffix + ".xyz")


def main(argv: list[str] | None = None) -> None:
    options = build_parser().parse_args(argv)

    print("\nStructure file with the reactant: " + options.reactant_path)
    print("Structure file with the product:  " + options.product_path)

    print(f"\nDonor index in the reactant structure: {options.reactant_donor}")
    print(f"Acceptor index in the reactant structure: {options.reactant_acceptor}")
    print(f"\nDonor index in the product structure: {options.product_donor}")
    print(f"Acceptor index in the product structure: {options.product_acceptor}")

    print("\nOutput file with the averaged structure: " + options.output_path + "\n")

    # python arrays are 0-based
    reactant_donor = options.reactant_donor - 1
    reactant_acceptor = options.reactant_acceptor - 1
    product_donor = options.product_donor - 1
    product_acceptor = options.product_acceptor - 1

    # reactant: donor-acceptor axis onto Z, midpoint at the origin
    reactant_symbols, reactant_positions = read_structure(options.reactant_path)
    reactant_positions, reactant_distance = align_da_to_z(
        reactant_positions, reactant_donor, reactant_acceptor
    )
    reactant_positions = round_to_xyz_precision(
        centre_da_midpoint(reactant_positions, reactant_acceptor)
    )

    write_xyz(
        aligned_path(options.reactant_path, "_DA_along_Z"),
        reactant_symbols,
        reactant_positions,
        "Reactant with D and A atoms along the Z-axis and midpoint at (0,0,0): "
        f"DA distance {reactant_distance:10.6f} Å",
    )

    # product: same treatment
    product_symbols, product_positions = read_structure(options.product_path)
    product_positions, product_distance = align_da_to_z(
        product_positions, product_donor, product_acceptor
    )

    # KNOWN BUG, DELIBERATELY NOT FIXED: this shifts the product structure using
    # `reactant_acceptor`, the acceptor index in the *reactant* file. The correct
    # index is `product_acceptor`. It is left as-is so that averaged structures
    # generated by earlier versions of this script -- and the proton potentials
    # derived from them -- stay reproducible. It only matters when the two
    # acceptor indices differ; fixing it would change the averaged geometry and
    # invalidate any downstream scan built on it.
    product_positions = round_to_xyz_precision(
        centre_da_midpoint(product_positions, reactant_acceptor)
    )

    write_xyz(
        aligned_path(options.product_path, "_DA_along_Z"),
        product_symbols,
        product_positions,
        "Product with D and A atoms along the Z-axis and midpoint at (0,0,0): "
        f"DA distance {product_distance:10.6f} Å",
    )

    # Check if DA distances are the same in the reactant and product structures
    if abs(reactant_distance - product_distance) > 1e-6:
        print(
            "\nThe donor acceptor distances in the reactant and product structures "
            f"are different: {reactant_distance} and {product_distance}"
        )
        print(
            "Donor and acceptor atoms are along the Z-axis and the midpoint is aligned)\n"
        )
        print(
            "Average structure is labeled by the DA distance in the reactant configuration\n"
        )

    # rotate the product around Z to minimize the RMSD to the reactant
    minimum_rmsd, angle = minimize_rmsd_rotation(reactant_positions, product_positions)

    print(
        f"\nMinimum RMSD: {minimum_rmsd:12.6f}   "
        f"Rotation angle is {180 * angle / math.pi:12.6f} degrees\n"
    )

    product_positions = round_to_xyz_precision(
        product_positions @ rotation_about_z(angle).T
    )

    write_xyz(
        aligned_path(options.product_path, "_DA_along_Z_aligned"),
        product_symbols,
        product_positions,
        "Product with D and A atoms along the Z-axis and aligned with reactant: "
        f"DA distance {product_distance:10.6f} Å",
    )

    write_xyz(
        options.output_path,
        reactant_symbols,
        average_structures(reactant_positions, product_positions),
        f"Average reactant/product configuration: DA distance {reactant_distance:10.6f} Å",
    )


if __name__ == "__main__":
    main()
